IF COL_LENGTH('dbo.BIEN_THE_SAN_PHAM', 'SoLuongLoi') IS NULL
BEGIN
    ALTER TABLE dbo.BIEN_THE_SAN_PHAM ADD SoLuongLoi INT NOT NULL CONSTRAINT DF_BTSP_SoLuongLoi DEFAULT (0);
END
GO

IF COL_LENGTH('dbo.YEU_CAU_DOI_TRA', 'MoTaChiTiet') IS NULL
BEGIN
    ALTER TABLE dbo.YEU_CAU_DOI_TRA ADD MoTaChiTiet NVARCHAR(1000) NULL;
END
GO

IF COL_LENGTH('dbo.YEU_CAU_DOI_TRA', 'PhuongThucHoanTien') IS NULL
BEGIN
    ALTER TABLE dbo.YEU_CAU_DOI_TRA ADD PhuongThucHoanTien NVARCHAR(50) NOT NULL CONSTRAINT DF_YCDT_PhuongThucHoanTien DEFAULT (N'BANK_TRANSFER');
END
GO

IF COL_LENGTH('dbo.YEU_CAU_DOI_TRA', 'GhiChuXuLy') IS NULL
BEGIN
    ALTER TABLE dbo.YEU_CAU_DOI_TRA ADD GhiChuXuLy NVARCHAR(1000) NULL;
END
GO

IF COL_LENGTH('dbo.YEU_CAU_DOI_TRA', 'AnhMinhChung') IS NULL
BEGIN
    ALTER TABLE dbo.YEU_CAU_DOI_TRA ADD AnhMinhChung NVARCHAR(255) NULL;
END
GO

IF COL_LENGTH('dbo.YEU_CAU_DOI_TRA', 'NgayCapNhat') IS NULL
BEGIN
    ALTER TABLE dbo.YEU_CAU_DOI_TRA ADD NgayCapNhat DATETIME2 NULL;
END
GO

IF COL_LENGTH('dbo.CHI_TIET_DOI_TRA', 'YeuCauDoiTraId') IS NULL
BEGIN
    ALTER TABLE dbo.CHI_TIET_DOI_TRA ADD YeuCauDoiTraId INT NULL;
END
GO

IF COL_LENGTH('dbo.CHI_TIET_DOI_TRA', 'ChiTietDonHangId') IS NULL
BEGIN
    ALTER TABLE dbo.CHI_TIET_DOI_TRA ADD ChiTietDonHangId INT NULL;
END
GO

IF COL_LENGTH('dbo.CHI_TIET_DOI_TRA', 'InspectionStatus') IS NULL
BEGIN
    ALTER TABLE dbo.CHI_TIET_DOI_TRA ADD InspectionStatus NVARCHAR(30) NOT NULL CONSTRAINT DF_CTDT_InspectionStatus DEFAULT (N'PENDING_INSPECTION');
END
GO

IF OBJECT_ID('dbo.HINH_ANH_DOI_TRA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.HINH_ANH_DOI_TRA (
        Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        YeuCauDoiTraId INT NOT NULL,
        DuongDanAnh NVARCHAR(500) NOT NULL,
        NgayTao DATETIME2 NOT NULL CONSTRAINT DF_HADT_NgayTao DEFAULT (SYSDATETIME()),
        CONSTRAINT FK_HADT_YCDT FOREIGN KEY (YeuCauDoiTraId) REFERENCES dbo.YEU_CAU_DOI_TRA(Id)
    );
END
GO

IF OBJECT_ID('dbo.LICH_SU_XU_LY_DOI_TRA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.LICH_SU_XU_LY_DOI_TRA (
        Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        YeuCauDoiTraId INT NOT NULL,
        NguoiXuLyId INT NULL,
        HanhDong NVARCHAR(80) NOT NULL,
        GhiChu NVARCHAR(1000) NULL,
        ThoiGian DATETIME2 NOT NULL CONSTRAINT DF_LSXLDT_ThoiGian DEFAULT (SYSDATETIME()),
        CONSTRAINT FK_LSXLDT_YCDT FOREIGN KEY (YeuCauDoiTraId) REFERENCES dbo.YEU_CAU_DOI_TRA(Id),
        CONSTRAINT FK_LSXLDT_TK FOREIGN KEY (NguoiXuLyId) REFERENCES dbo.TAI_KHOAN(Id)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CTDT_YCDT')
    ALTER TABLE dbo.CHI_TIET_DOI_TRA WITH NOCHECK ADD CONSTRAINT FK_CTDT_YCDT FOREIGN KEY (YeuCauDoiTraId) REFERENCES dbo.YEU_CAU_DOI_TRA(Id);
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CTDT_CTDH')
    ALTER TABLE dbo.CHI_TIET_DOI_TRA WITH NOCHECK ADD CONSTRAINT FK_CTDT_CTDH FOREIGN KEY (ChiTietDonHangId) REFERENCES dbo.CHI_TIET_DON_HANG(Id);
GO

IF OBJECT_ID('dbo.HINH_ANH_DOI_TRA', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HADT_YeuCauDoiTraId' AND object_id = OBJECT_ID('dbo.HINH_ANH_DOI_TRA'))
    CREATE INDEX IX_HADT_YeuCauDoiTraId ON dbo.HINH_ANH_DOI_TRA(YeuCauDoiTraId, Id);
GO

IF OBJECT_ID('dbo.LICH_SU_XU_LY_DOI_TRA', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LSXLDT_YeuCauDoiTraId_ThoiGian' AND object_id = OBJECT_ID('dbo.LICH_SU_XU_LY_DOI_TRA'))
    CREATE INDEX IX_LSXLDT_YeuCauDoiTraId_ThoiGian ON dbo.LICH_SU_XU_LY_DOI_TRA(YeuCauDoiTraId, ThoiGian);
GO

IF OBJECT_ID('dbo.CHI_TIET_DOI_TRA', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CTDT_YeuCauDoiTraId' AND object_id = OBJECT_ID('dbo.CHI_TIET_DOI_TRA'))
    CREATE INDEX IX_CTDT_YeuCauDoiTraId ON dbo.CHI_TIET_DOI_TRA(YeuCauDoiTraId);
GO

UPDATE dbo.YEU_CAU_DOI_TRA
SET TrangThai = CASE TrangThai
    WHEN 'PENDING' THEN 'CHO_DUYET'
    WHEN 'APPROVED' THEN 'DA_DUYET'
    WHEN 'REJECTED' THEN 'TU_CHOI'
    ELSE TrangThai
END
WHERE TrangThai IN ('PENDING', 'APPROVED', 'REJECTED');
GO
